 # Creating Series

There are multiple ways to create a pandas series:

In [6]:
import numpy as np
import pandas as pd

In [6]:
labels = ["a", "b", "c"]
my_list = [10,20,30]
arr = np.array([10,20,30])
dict = {1:10,2:20,3:30}

In [8]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [11]:
pd.Series(dict)
# dict ki jo ki hoti h vhi labels bn jati h

1    10
2    20
3    30
dtype: int64

# Creating a DataFrame

In [7]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

# dict me already key hoti h jise column name ki trh liya jata h list me nhi

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selection and Indexing of columns

In [9]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [27]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

# Creating a new column

In [28]:
df2["Designation"] = ["Doctor","Eng","Doctor","Eng"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

# Removing a column

In [29]:
df2.drop("Designation",axis = 1,inplace = True )

# axis = 1 karne mtlb vo degignation ko column name me dhundega fir delete karega (for vertical)
# axis = 0 ka mtlb vo row name me dekhega (for horizontal)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
 # df2.drop(["City", "Salary"],axis = 1)

In [30]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selecting Rows

In [31]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [32]:
df2.iloc[3] # index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# Selecting Subset of rows and columns

In [33]:
df2.loc[[0,1]][["Salary","City"]]

   Salary      City
0   65000  New York
1   70000     Paris

# Conditional Selection

In [34]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#I only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [11]:
#I only want poeple whose age is above 30 and their city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris") ]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

# finding missing data

In [13]:
import numpy as np
import pandas as pd

In [15]:
data_1 = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df3 = pd.DataFrame(data_1)
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [16]:
df3.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [17]:
df3.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [18]:
df3.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Removing missing data

In [19]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [20]:
df3.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [24]:
df3.dropna(thresh = 3) 
# mtlb jitni thresh ki value h row me kam se kam utni non-value rhni chahiye jisme hogi vo rhega baki drop ho jayege

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Filling the missing data

In [25]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [26]:
df3.fillna(0) # to apply inplace = true karna padega

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [27]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
values = {"A":0,"B":100,"C":200,"D":400}
df3.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  200.0  400.0
4  5.0  5  200.0    5.0

In [ ]:
# drop row wise hota h 
# selection aur fillna column wise hota h

In [29]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
df3.fillna(df3.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# Merging 2 dataframes

In [31]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [32]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [33]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [34]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [36]:
pd.merge(employees,salaries,on = "employee_id",how = "inner") # merge common columns ke basis par hota h

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [37]:
pd.merge(employees,salaries,on = "employee_id",how = "outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [38]:
pd.merge(employees,salaries,on = "employee_id",how = "left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [39]:
pd.merge(employees,salaries,on = "employee_id",how = "right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# Concatination of 2 dataframes

In [40]:
df4 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df5 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [41]:
df4

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [42]:
df5

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [43]:
pd.concat([df4,df5])
# column wise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [44]:
pd.concat([df4,df5],axis = 1)
# row wise

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Joining 2 data frames

In [50]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [51]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [52]:
df2

   score
2     85
3     90
4     75

In [53]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [56]:
df1.join(df2,how = "outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [57]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# GroupBy

In [58]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [59]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [65]:
# Group by Category and calculate the sum of Sales
cat = df.groupby("Category")["Sales"].sum()
cat

# for loop to see the categorise data
 # for i,v in cat:
  #  print(i)
  #  print(v)

Category
A    570
B    930
Name: Sales, dtype: int64

In [66]:
# Group by Store and calculate the sum of Sales
store = df.groupby("Store")["Sales"].sum()
store

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [67]:
# Group by multiple columns
# Group by Category and Store
sol = df.groupby(["Category","Store"])["Sales"].sum()
sol

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [68]:
sol = df.groupby(["Store","Category"])["Sales"].sum()
sol

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

# Aggregation

In [69]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [70]:
df["Sales"].mean()
"""mean median min max count std """

187.5

In [77]:
df["Sales"].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [ ]:
# mode() function baaki functions (sum, mean, min, max, count, std, median) jaisa scalar (single value) return nahi karta

# Pivot Table

In [78]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    174     37   John  January      Q1
1  2023-01-02       B   West    323     89   Mary  January      Q1
2  2023-01-03       C  North    791     69    Bob  January      Q1
3  2023-01-04       D  South    598     36  Alice  January      Q1
4  2023-01-05       A   East    339     22   John  January      Q1
5  2023-01-06       B   West    436     60   Mary  January      Q1
6  2023-01-07       C  North    526     87    Bob  January      Q1
7  2023-01-08       D  South    247     69  Alice  January      Q1
8  2023-01-09       A   East    503     98   John  January      Q1
9  2023-01-10       B   West    776     97   Mary  January      Q1
10 2023-01-11       C  North    871     36    Bob  January      Q1
11 2023-01-12       D  South    899     31  Alice  January      Q1
12 2023-01-13       A   East    678     23   John  January      Q1
13 2023-01-14       B   West    282     64   Mary  January      Q1
14 2023-01-15       C  North    153     17    Bob  January      Q1
15 2023-01-16       D  South    634     56  Alice  January      Q1
16 2023-01-17       A   East    545     84   John  January      Q1
17 2023-01-18       B   West    768     14   Mary  January      Q1
18 2023-01-19       C  North    260     32    Bob  January      Q1
19 2023-01-20       D  South    266     32  Alice  January      Q1

In [81]:
pd.pivot_table(df,values = "Sales",index = "Region",columns = "Product") # mean aaya h

Product      A      B      C      D
Region
East     447.8    NaN    NaN    NaN
North      NaN    NaN  520.2    NaN
South      NaN    NaN    NaN  528.8
West       NaN  517.0    NaN    NaN

In [82]:
pd.pivot_table(df,values = "Sales",index = "Region",columns = "Product",aggfunc = "median") # median aaya h

Product      A      B      C      D
Region
East     503.0    NaN    NaN    NaN
North      NaN    NaN  526.0    NaN
South      NaN    NaN    NaN  598.0
West       NaN  436.0    NaN    NaN

In [84]:
pivot2 = pd.pivot_table(df,values = (["Sales","Units"]),index = "Region" ,columns = "Product")
pivot2
# values must be numeric

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     447.8    NaN    NaN    NaN  52.8   NaN   NaN   NaN
North      NaN    NaN  520.2    NaN   NaN   NaN  48.2   NaN
South      NaN    NaN    NaN  528.8   NaN   NaN   NaN  44.8
West       NaN  517.0    NaN    NaN   NaN  64.8   NaN   NaN

# Cross Tab

In [85]:
pd.crosstab(df["Region"],df["Product"])
# crosstab is used for counting purpose

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [86]:
pd.crosstab(df["Product"],df["Region"])

Region   East  North  South  West
Product
A           5      0      0     0
B           0      0      0     5
C           0      5      0     0
D           0      0      5     0

# DataFrames Basic Operations

In [102]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [103]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [89]:
df1.shape

(5, 3)

In [90]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [91]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [92]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [93]:
df1["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

# DataFrames Applying Function

In [104]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [105]:
def square(x):
    return x**2

In [106]:
df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [107]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [108]:
df1["B"] = df1["B"].apply(square)

In [109]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [110]:
df1["D"] = df1["A"].apply(square)

In [111]:
df1

   A     B    C   D
0  1   100  100   1
1  2   400  200   4
2  3   900  300   9
3  4  1600  400  16
4  5  2500  500  25

In [ ]:
# df1["D"] = df1["A"].apply(lambda x : x**2)
# aise bhi kar sakte h

In [ ]:
# to check file path
# import os
# os.getcwd()